### PR TITLE
Edit README.md with format guidelines

### PR DESCRIPTION
**Pull request by DavidAfonsoValente**
Automatic Code Formatter on code push according to Julia format

#29

### CODE REVIEW

**Comment by samuelbelko** [comment]
Hi! There were some preferences on which style to use ([link](https://github.com/jbrea/BayesianOptimization.jl/pull/27#discussion_r1150623069)), it would be great if you could add a new file `.JuliaFormatter.toml` to the root level of the project containing a single line `style = "sciml"` to [configure  the formatter](https://docs.juliahub.com/JuliaFormatter/OWZnm/0.14.7/config/) to use [SciMLStyle](https://github.com/SciML/SciMLStyle). If you like you could also add a [badge](https://github.com/SciML/SciMLStyle#code-style-badge) to `README.md` 👍

**Comment by samuelbelko** [comment]
Thanks!

**Comment by jbrea** [comment]
For some reasons I don't understand the automatic PR creation fails, but I'm not sure we even want to do this. An alternative would be to just check that the new files are correctly formatted, as e.g. [here](https://github.com/SciML/DataDrivenDiffEq.jl/blob/master/.github/workflows/FormatCheck.yml). Opinions?

**Comment by DavidAfonsoValente** [comment]
I agree, we could just make sure we run the formatter locally before every push

**Comment by samuelbelko** [comment]
I like the alternative solution as it is done in the other project, maybe we can mention it somewhere (readme / docs) what the preferred style is.

**Pull request closed without merging**
